---
# tasks file for filebeat_configure
- name: Filebeat configuration for jenkins
  template:
    src: ../templates/jenkins/filebeat.yml
    dest: /etc/filebeat
  when: {{ inventory_hostname }} == "jenkins"
- name: Filebeat configuration for elk
  template:
    src: ../templates/elk/filebeat.yml
    dest: /etc/filebeat
  when: {{ inventory_hostname }} == "elk-server"
- name: ensure filebeat is running
  systemd: state=started name=filebeat

